# Generated by Django 6.0.3 on 2026-05-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_created_at_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
