# Generated by Django 6.0.3 on 2026-05-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_application_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
