# Generated by Django 6.0.3 on 2026-03-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
